name: Build App
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["16", "18"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }} 
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["16", "18"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download uploaded build file
        uses: actions/download-artifact@v3
        with:
          name: build-files