name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Repo codes
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test 
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deployment
        run: echo deployment ....
    