name: Test React App
on: push
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Repo codes
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test 
      
    